// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpmJ-sYlPE4mAjR5EbLGh5RqmHksyUv80',
    appId: '1:166096416684:web:8afeaa24e06b8aa1bb9409',
    messagingSenderId: '166096416684',
    projectId: 'exam2-97601',
    authDomain: 'exam2-97601.firebaseapp.com',
    storageBucket: 'exam2-97601.firebasestorage.app',
    measurementId: 'G-G00QVKVFZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTmE7ICpYUzLGL7e-QNbpRCsCaK25aGdo',
    appId: '1:166096416684:android:72fe1cca93e20381bb9409',
    messagingSenderId: '166096416684',
    projectId: 'exam2-97601',
    storageBucket: 'exam2-97601.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz_rmbJ6C1KNrKgP9Ig650FJMGowYE6Aw',
    appId: '1:166096416684:ios:a9f368128610ca82bb9409',
    messagingSenderId: '166096416684',
    projectId: 'exam2-97601',
    storageBucket: 'exam2-97601.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz_rmbJ6C1KNrKgP9Ig650FJMGowYE6Aw',
    appId: '1:166096416684:ios:a9f368128610ca82bb9409',
    messagingSenderId: '166096416684',
    projectId: 'exam2-97601',
    storageBucket: 'exam2-97601.firebasestorage.app',
    iosBundleId: 'com.example.studentManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpmJ-sYlPE4mAjR5EbLGh5RqmHksyUv80',
    appId: '1:166096416684:web:0736a1ee76cad71ebb9409',
    messagingSenderId: '166096416684',
    projectId: 'exam2-97601',
    authDomain: 'exam2-97601.firebaseapp.com',
    storageBucket: 'exam2-97601.firebasestorage.app',
    measurementId: 'G-1YP2NJ18YR',
  );
}
